{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "t3codes.serviceAccountName" . }}
  labels:
    {{- include "t3codes.labels" . | nindent 4 }}
{{- end }}
